#!/usr/bin/env python3
import sys
from datetime import datetime

def main(inp, outp):
    with open(inp, 'r', encoding='utf-8') as f:
        data = f.read().splitlines()
    kv = {}
    for line in data:
        line = line.strip()
        if not line or line.startswith('#'):
            continue
        if '=' in line:
            k, v = line.split('=', 1)
            kv[k.strip()] = v.strip()
    with open(outp, 'w', encoding='utf-8') as f:
        f.write('// Auto-generated by gen_config.py\n')
        f.write(f'// Generated at {datetime.now()}\n')
        for k, v in kv.items():
            f.write(f'#define {k} {v}\n')
        f.write('\n')
        f.write('#pragma once\n')
        f.write('#define CODEGEN_DEMO_CONFIG_LOADED 1\n')

if __name__ == '__main__':
    if len(sys.argv) != 3:
        print('Usage: gen_config.py <config.in> <config.h>')
        sys.exit(1)
    main(sys.argv[1], sys.argv[2])
