#include <iostream>
#include <vector>
#include <string>

#include "config.h"
#include "ops_gen.h"
#include "messages.pb.h"

// From qrc_resources.cpp generated by rcc.py
extern std::vector<std::string> demo_resources;

// From moc_widget.cpp generated by moc.py
extern const char** metaInfo_Widget();

int do_calc(); // from calc.cpp
int ui_action(); // from ui.cpp
int process_operations(); // from process.cpp
void send_event(int, const std::string&); // from event.cpp
int analyze_data(); // from analyzer.cpp

int main() {
  // Use generated config defines
  std::cout << "CODEGEN_DEMO_CONFIG_LOADED: " << CODEGEN_DEMO_CONFIG_LOADED << "\n";

  // Use generated ops
  int a = 7, b = 5;
  int add = eval(OpKind::ADD, a, b);
  int mul = eval(OpKind::MUL, a, b);
  std::cout << "eval(ADD): " << add << ", eval(MUL): " << mul << "\n";

  // Use generated proto-like
  Person p; p.id = 1; p.name = "Alice";
  std::cout << "Person Serialize: " << p.Serialize() << "\n";

  // Use generated resource list
  std::cout << "Resources (" << demo_resources.size() << "):\n";
  for (auto &r : demo_resources) std::cout << "  - " << r << "\n";

  // Use generated moc-like
  auto meta = metaInfo_Widget();
  (void)meta;

  // Cross-translation-unit calls
  std::cout << "do_calc(): " << do_calc() << "; ui_action(): " << ui_action() << "\n";
  std::cout << "process_operations(): " << process_operations() << "\n";
  send_event(12345, "test_event");
  std::cout << "analyze_data(): " << analyze_data() << "\n";
  return 0;
}
